name: LaTeX CI

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: Slides-2025-MTACR/presentation.tex
          compiler: latexmk
          args: -pdf -file-line-error -interaction=nonstopmode

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Slides-2025-MTACR/presentation.pdf
